# Generated by Django 4.2.6 on 2023-10-19 15:57

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='doctor_photos/')),
            ],
        ),
        migrations.CreateModel(
            name='MyExpenses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expense_name', models.CharField(max_length=300, verbose_name='Expense Name')),
                ('paid_amount', models.CharField(max_length=100)),
                ('expense_date', models.DateField(auto_now_add=True)),
                ('expense_bill_image', models.ImageField(blank=True, null=True, upload_to='MyExpenses_photos/')),
                ('expense_details', models.TextField(default='Details not provided', null=True, verbose_name='Expense Details')),
            ],
            options={
                'verbose_name': 'My Expense',
            },
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('patient_photo', models.ImageField(blank=True, null=True, upload_to='Patient_photos/')),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], max_length=1)),
                ('age', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(120)])),
                ('contact_number', models.CharField(max_length=15, unique=True)),
                ('issue_description', models.TextField(blank=True, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('government_id_type', models.CharField(blank=True, choices=[('AC', 'Aadhar Card'), ('DL', 'Driving Licence'), ('VI', 'Voter ID'), ('PC', 'PAN Card'), ('PP', 'Passport'), ('OT', 'Other')], max_length=20, null=True)),
                ('government_id_number', models.CharField(blank=True, max_length=20, null=True)),
                ('assigned_doctor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_patients', to='dental.doctor')),
            ],
        ),
        migrations.CreateModel(
            name='PatientPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_date', models.DateField(auto_now_add=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('payment_to_account', models.CharField(choices=[('Dr. Shruti Priya', 'Dr. Shruti Priya'), ('Chitrakoot', 'Chitrakoot'), ('Cash', 'Cash'), ('Account Not Selected', 'Account Not Selected')], default='Account Not Selected', max_length=50)),
                ('patient_bill_image', models.ImageField(blank=True, null=True, upload_to='PatientPayment_photos/')),
                ('description', models.TextField(blank=True, null=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dental.patient')),
            ],
            options={
                'verbose_name': 'Patient Payment',
            },
        ),
    ]
